### ISSUE TITLE
 2021 Jan. Release Plan 

### ISSUE THREAD

**Issue by debuggy** [microsoft/openpaimarketplace#152]
# Release Manager
@debuggy

# End Game

code freeze: Dec. 24
Bug bash: Dec. 28 ~ Jan. 8

# Plan Items

## Deployment and use  #165 
- [x] ⭐ Deploy database with more rubustness -- @debuggy
- [x] ⭐ Blob is not required when using job template  -- @debuggy 

## market list page
- [x] ⭐ Add search bar -- @debuggy 

## Create templates

- [x] Refine UI of marketplace create page -- @yangou1988 @yiyione ETA: 12/18 #163

- [x]  ⭐ Create data item (basic feature: upload data to Azure blob)
> - [x] UI design -- @yangou1988 @TobeyQin ETA: 12/9
> - [x] Feature implementation -- @yiyione ETA: 12/18

- [x]  ⭐ Create item from job list, or add "save to template" feature -- for discussion --@everyone

## Documentation
- [x] ⭐Refine manual book of marketplace deploy flow #154 -- @debuggy @TobeyQin @yiyione ETA: 12/24
- [x] Deployment flow discussion @debuggy @yiyione @TobeyQin ETA: 12/11

# Test Cases
Test owner: @TobeyQin 

- [x] Marketplace home page components and items #185 #186
- [x] Download dataset
- [x] Upload dataset #169 #170 #171 #172 #173 #174 
- [x] Create job template #187 
- [x] Delete redundant items(using delete API) #188
- [x] Run each templates successfully @SwordFaith 
- [x] Successfully deploy marketplace follow the document @debuggy

# Backlog
- [x] 拖拽式UI
- [x] Version control
- [x] Easily transfer GitHub project to Marketplace 
- [x] Introducing marketplace in submit job page
- [x] Export template to marketplace from job list and job detail page

## Examples Template
- [ ] P2 - NNI tasks [NNI student program](https://github.com/microsoft/ai-edu/tree/master/G-%E5%AE%9E%E8%B7%B5%E9%A1%B9%E7%9B%AE/NNI-Student-Program-2020)
    (controller, trials) -- @TobeyQin @qfyin (+liuzhe-lz )
 
- [ ] P2 - NNFusion example -- @TobeyQin  @qfyin (+wenxaing)
## Submission Related Backlog
- [x] P2 ~Submit job ui should show protocol prerequisites parts https://github.com/microsoft/openpaimarketplace/issues/73 @debuggy  @yiyione @TobeyQin ~  
- [x] P1 - ~Add feature to select dataset by click checkbox -- @hzy46~ 
- [x] P2 - Refine Submit Job page layout -- @yangou1988
- [x] P0 - Fix data storage config mismatching issue -- @debuggy 

- [x] P1 - add "Upload" feature for dataset, set upload standard and workflow
            1.  For public dataset (Specify the source path)
            2.  For private dataset (Could we store data to Azure blob? or GitHub?)

## Collaboration with SHAIIC -- discussion
- [x] Marketplace deploy flow
- [x] Training examples
- [x] Jupyter Notebook interaction
