### ISSUE TITLE
New Job Submission Design

### ISSUE THREAD

**Issue by Morningssir** [microsoft/openpaimarketplace#206]
## Introduction
The new job submission design will make new attempts in _UI design_, _data storage_ and _css solution_. The original page has structural redundancy in expressing job data. The new design idea will introduce _redux_ as the data storage scheme and _job-protocol-schema_ as the data storage format. This will greatly reduce the call and parameter transfer between components and make the structure as clear as possible. At the same time, it will cooperate with the prototype design to complete the construction of the new UI interface. On this basis, the new design plan will try to use a new css solution, combining _functional css_ and _styled components_ to achieve the unification and standardization of styles.
## Issues / Motivations

- [ ] Redundant representation in job data. JobProtocol is based on job-protocol-schema to represent the overall form of job data, and it is also the carrier of yaml parsing. But in the component, a class of data is also parsed from JobProtocol to represent basic info, taskroles, parameters and secrets
- [ ] Complex parameter transfer between components
- [ ] Ensure the unity of css style and introduce new related technologies
- [ ] Standard definition of css unified theme
- [ ] Prototype design issues involved in multiple task roles

## Proposals / Solutions

- [ ] Introduce redux technology, store data in store, and provide components with direct access to store permissions. Any modification of job-protocol directly requests the corresponding action, triggering the reducer to update the state
- [ ] Introduce redux-saga as redux middleware technology to handle async requests
- [ ] tachyons+styled system as a css solution. Develop theme according to tachyons standard

## Work Plan

- [ ] Transfer the original model and utils code
- [ ] Build the redux structure, complete the connection between the components and the store, and test the accuracy of data access and action requests
- [ ] Rely on the prototype to complete the refactoring of the sidebar. Finish modules such as parameters and environment variables
- [ ] Finish form components and complete the construction of job basic info. *responsive issues
- [ ] Design the demo of multiple task roles

**Comment by yiyione** [comment]
1. `case 2.ii When the page width is greater than 1024 pixels, the submission page is displayed in three columns.`
  Only show 2 columns when show the sidebar.
2. `case 3.iv Retry Count should be 1 by default and Retry Count can be modified correctly.`
  Default retry count is 0.
3. `case 3.ix Task Retry Count should be 1 by default and Task Retry Count can be modified correctly.`
  Default task retry count is 0.
