### ISSUE TITLE
[MP restserver] marketplace item schema add access control fileds

### ISSUE THREAD

**Issue by SwordFaith** [microsoft/openpaimarketplace#213]
## Introduction

#210 work item 1: add groupList, isPublic, isPrivate property to it. Add access control related fields.

## Issues / Motivations

Support access control function to marketplace items

## Proposals / Solutions

Change item schema. Both in model define and in swagger.

## Work Plan

* [ ] Update marketplace item model schema
* [ ] Update swagger marketplace item schema

## Test cases

* [ ] query /items api, item in response item list should have groupList, isPublic, isPrivate fields
    * [ ] test on type={data, old, template} and all -> /items 
* [ ] swagger schema should be updated
