### ISSUE TITLE
[MP webportal] Add access control to "Delete" button in item detail

### ISSUE THREAD

**Issue by SwordFaith** [microsoft/openpaimarketplace#216]
## Introduction

Delete is only available for item author or admin, it should be disabled if user is neither item author or admin. #210 work item 4

## Issues / Motivations

Delete operation should be disabled for user only have view privilege.

## Proposals / Solutions

Check with (item.author==username or user.isAdmin) locally, if no delete authorization, the delete button should be disabled (hide or grayed). OnClick the enabled button, webportal will send a delete request to /items/{itemId} api, the api will check auth again. If response 200 OK, webportal should show a success delete info and remove this item locally. Otherwise, webportal should prompt an error. Backend db consistency issue ?

## Work Plan

* [x] Add check auth logic and state in webportal
* [x] Add render logic affected by delete button status
* [ ] Address front-end and back-end consistency issue if need

## Test cases

* [ ] For username == item.author || user.isAdmin item, delete button is enabled
* [ ] For username != item.author && !user.isAdmin item, delete button is disabled
* [ ] Click disabled button, no request query issued
* [ ] Click enabled button, item correctly delete in webportal (no display) and restserver (check by get /items/{itemId})
* [ ] Use admin change item.author to specific user, after refresh the disabled button should be enabled
