### ISSUE TITLE
[MP restserver] validation post item protocol

### ISSUE THREAD

**Issue by SwordFaith** [microsoft/openpaimarketplace#222]
## Introduction

Marketplace restserver has validation to post /items json body, but no validation for protocol format.

## Issues / Motivations

Marketplace restserver has validation to post /items json body, but no validation for protocol format.

## Proposals / Solutions

Add validation to protocol format, make it at least a regular yaml string. It will be better to make the protocol follow [openpai-protocol schema](https://github.com/microsoft/openpai-protocol/blob/master/schemas/v2/schema.yaml)

## Work Plan

* [x] Add validation to protocol field check if it is a yaml string
* [x] Add validation to protocol field check if it is a openpai-protocol

## Test cases

* [ ] Throw error when protocol field is not a yaml string
* [ ] Throw error when protocol field is not an openpai-protocol
* [ ] Create item successfully when protocol field is an openpai-protocol
