### ISSUE TITLE
[ORM filter] For pai template selection, enhance filter to marketplace item

### ISSUE THREAD

**Issue by SwordFaith** [microsoft/openpaimarketplace#228]
## Introduction

![image](https://user-images.githubusercontent.com/18397468/109491839-0bcc0c80-7ac5-11eb-89f7-5fed27fded5b.png)

Currently, pai add support for template selection from marketplace, but for personal template only.
It will be better to support suggestion with strategy, like latest used, user input string likelihood, prerequisite suggestion etc.

## Issues / Motivations

It will be better to support suggestion with strategy, like latest used, user input string likelihood, prerequisite suggestion etc.

## Proposals / Solutions

Add init or migration logic in model_init_handler

## Work Plan

- [x] Check if marketplace item table exists and match model
- [x] If not match, do table schema migration

## Test cases

- [ ] New code should have no effect to new deploy marketplace process
- [ ] If schema not match current version, should do schema migration
