### ISSUE TITLE
2021 March Release Plan

### ISSUE THREAD

**Issue by debuggy** [microsoft/openpaimarketplace#233]
## Release Manager
@SwordFaith 

## End Game

Code Freeze Date:  TBD
Bug Bash Date: TBD ~ TBD

## Test Plan
A link to the test plan

### Save to template -- P0  #247 ETA: 3.19 test owner @yiyione
- [x] design doc #253 @debuggy ETA: 3.12
- [x]  Add save to template in new submission page #259 
- [x]  Save to template dialog with default description #247
- [x]  Save to template dialog add share to option #254
- [x]  Refine template selection #255
- Share logic:
    - share template to *groups*
    - select shared/my/official template: order, number
    - visibility
- Implementation:
    - Backend:
        - bring group info in api: get/post/put/delete group
    - UI
        - Display shared

### Item process experience -- P0
- [x] Design doc #249 @SwordFaith ETA: 3.12 discuss
- Implementation:
    - [x] Create (group)  Create data template simplify #246 @yiyione @suiguoxin 
    - [x] Copy (not yet) #243 @suiguoxin 
    - [x] List (group, source) #245 show rules testowner: @debuggy
    - [x] Edit (not yet) #205 testowner: @debuggy

Issues:
- [x] copy
  - [x] unable to copy private template: 403 Forbidden
  - [x]  set to `public` doesn't take effect 
  - [x] jump to new template after copying successfully
- [x] create
  - [x] create from your job : open another page when click on job name
  - [x] create completed page: 1) click on `marketplace`: no effect 2) click on   `back to market place`: there should be no warning

### Prerequisites (discuss with zhiyuan and ouyang) 
- Design doc (For backend) @hzy46 @TobeyQin  ETA:  TBD
- Marketplace item schema/protocol #244 

### New submission page #206 testowner: @hzy46 @SwordFaith @debuggy 
- [x] New submission page
- [x] Yaml editor page
- [x] Secrets and custom image auth
- [x] Hived SKU
- [x] SSH config
- [x] team storage
- [x] Convert between old and new page
- [x] submit, import and export

### Document -- P1
- [x] Trouble Shooting (need to be update) 
    - [x] migrate db @SwordFaith ETA: 3.11
- [x] Refine Document (need to be update)
    - [x] deploy doc: migrate db @SwordFaith ETA: 3.11
- [ ] Autotest all marketplace official templates #140 @yiyione 
- [x] ZenHub investigation and practice design @TobeyQin @yiyione  ETA: 3.12
 
### Create from job list -- P1 test owner: @debuggy
- [x] design doc @yiyione #256 
- [x] ui design ouyang
- [x] Implementation
- [x] Docker image could not edited when creating items

### Exp Improvement Items -- P1
- [ ] Back to market list #169 @debuggy 

### Bug Fix -- P1
- [ ] Multiple taskrole webportal conversion error #128 @Morningssir 
- [ ] Webportal generate job protocol wrong upload path #133 
- [ ] In template detail description page, "marketplace list" doesn't work #184 

## Backlog
- [x] TBD
